---
title: "Assignment 06"
format: html
embed-resources: true
author: Sarah Krause, Miguel Villa, and Johnny Willing
---

## Exercise 02

The paper whose findings we intend to reanalyze is Finkelstein et al.'s (2012) "The Oregon health insurance experiment: Evidence from the first year," which has replication data and code publicly available from the National Bureau of Economic Research [here](https://www.nber.org/research/data/oregon-health-insurance-experiment-data). The paper assesses the outcomes of a randomized experiment in which Oregon households entered into a lottery to gain access to Medicaid. 89,924 individuals registered for the lottery, of which 35,169, representing 29,664 households, were selected. One year after the individuals in these households were made eligible to enroll, Finkelstein et al. surveyed them on their health and financial strain as well as accessed administrative data for further analyses. Because not all individuals in selected households ended up being eligible for Medicaid, and some others failed to apply, not all of the selected individuals participated in Medicaid. Finkelstein et al. produce both ITT and LATE estimates; for simplicity, our reanalysis uses one of the ITT estimates.

@Sarah and @Miguel - which one do you want to do? I was thinking maybe self-reported health good/very good/excellent or has a usual place of clinic-based care (in tables IX and X). One concern - they do some reweighting based on the fact that some households had two individuals that entered the lottery, which increased their chance of being accepted. 

### Citations for data source and paper

**Paper:**

Finkelstein, A., Taubman, S., Wright, B., Bernstein, M., Gruber, J., Newhouse, J. P., Allen, H., Baicker, K., & Oregon Health Study Group. (2012). The Oregon health insurance experiment: Evidence from the first year. *The Quarterly Journal of Economics, 127(3)*, 1057–1106. https://doi.org/10.1093/qje/qjs020

**Data source:**

Finkelstein, A. (2013). Oregon health insurance experiment public use data \[Data set\]. National Bureau of Economic Research. https://www.nber.org/research/data/oregon-health-insurance-experiment-data
